### ISSUE TITLE
Example usages

### ISSUE THREAD

**Issue by Zalastax** [p5-types/p5.ts#1]
It would be great if there were some example repositories that we can link to.
We need examples for: local mode, global mode, p5.dom, and p5.sound.

**Comment by mictadlo** [comment]
https://github.com/troysandal/p5js-typescript-fusebox

**Comment by mictadlo** [comment]
https://github.com/GoSubRoutine/Ball-in-the-Chamber/tree/master/instance

**Comment by Zalastax** [comment]
Thanks!
I'll look into these as soon as I can.

**Comment by Zalastax** [comment]
I've set up an example project using webpack in the examples/webpack folder.
Next step is to look into how one can use p5.dom and p5.sound with TypeScript.
