### ISSUE TITLE
P5 inheritance 

### ISSUE THREAD

**Issue by vanpana** [p5-types/p5.ts#10]
I want to extend the p5 library in order to have error text on various locations on the screen. Right now, my class looks like:

```typescript
import * as p5 from 'p5';

export class CustomP5 extends p5 {
  ...
  constructor(sketch, htmlElement) {
    super(sketch, htmlElement);

    // Set tooltip error variable
    this.resetTooltipError();
  }

  setSetup(setupFunction) {
    super.setup = () => {
      setupFunction();
      this.setupAdditional();
    }
  }

  setDraw(drawFunction) {
    super.draw = () => {
      drawFunction();
      this.drawAdditional();
    };
  }

  showTooltipError() {
    ...
  }
```
Everything is working fine, except some properties. For example, if I access ```super.height``` I'll get 0, while if I access ```this.height``` I'll get the actual height. But, when accessing ```this.height``` I get an error saying that height isn't defined in CustomP5, which is right, but at the same time confusing.

Is there a reason why ```super.height```, ```super.mouseX```, ```super.mouseY``` don't work, while ```super.draw``` or ```super.mousePressed``` are working correctly?

PS: I'm quite new to js and ts, so be patient if I'm wrong, please.

**Comment by Zalastax** [comment]
I believe that the reason they are not working is because p5 is not actually based on ES6 classes. As a user of p5 you are usually not meant to extend p5. If you still want to do this, ask on the main issue board about how to extend p5 using ES6 classes. If it's supported, translating their suggested ES6 code to TS should be easy.

**Comment by wuyudi** [comment]
Now it's based on ES6 class. I rewrite them.
