### ISSUE TITLE
How can I generate types for p5play?

### ISSUE THREAD

**Issue by quinton-ashley** [p5-types/p5.ts#115]
p5play is a p5.js library and it has JSDoc comments already.

I tried generating type definitions but p5play.d.ts file only contained this:

```
//# sourceMappingURL=p5play.d.ts.map
```

Do I have to import types from p5.js? I tried to do that like this at the top of the file but it didn't work.

```js
/// <reference types="p5" />

const p5 = require('../../types/p5');
```

just added exports {}

```
exports {}
//# sourceMappingURL=p5play.d.ts.map
```

I'm a total noob to this so any help would be greatly appreciated!

**Comment by asukaminato0721** [comment]
if jsdoc -> dts file, <https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html>

this project is for json -> dts file.

json's content is from yuidoc.

**Comment by quinton-ashley** [comment]
thank you! but yeah I already figured it out
