### ISSUE TITLE
Geometry methods (beginGeometry, endGeometry, etc) are not available.

### ISSUE THREAD

**Issue by whyi** [p5-types/p5.ts#119]
Hello, I tried to use those methods but they seem to be not available.

I think these should be added somewhere (do not know what file is the right one).

```Typescript
    interface p5InstanceExtensions {
        beginGeometry(): void;
        endGeometry(): Geometry
    }
```

If the above is right, can someone briefly guide me to which file they should be placed, so that I can make a pull request?

Thank you.

**Comment by asukaminato0721** [comment]
the problem is, now the type is from yui-doc, this repo is merely a converter.

> which file they should be placed, 

<https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/p5>

here.
