### ISSUE TITLE
nodegit

### ISSUE THREAD

**Issue by Spongman** [p5-types/p5.ts#12]
is there any chance we can remove the `nodegit` dependency, maybe to a different project?

i have never actually been able to build this project due to the `nodegit` dependency - it never builds. it seems unnecessary to check out the whole p5 repo when the `data.json` can just be extracted directly from the `p5.js` file, which is available online.

**Comment by Zalastax** [comment]
Sure, go ahead!
I didn't think of extracting `data.json` from the website 😳

My idea was that generating types should be automatable, preferably with the possibility to get the deltas for each version as well; this caused me to go overboard on the scripts. Another idea was that I don't want to rely on the git version available on the system and therefore I went with `nodegit`. Unfortunately, `nodegit` is very tedious to use and doesn't always build...

It *would* be nice if we could automate fetching the latest released  `data.json` + printing the [files for tsconfig.json](https://github.com/p5-types/DefinitelyTyped/blob/607aff8f56075c9540c805d17569eaec9d478de0/types/p5/tsconfig.json#L15-L72), but that's about it. I think I can manage opening some PR's once in a while.

**Comment by wuyudi** [comment]
I was currently confused by the nodegit (and then I decided just to remove them for package.json.)

so it was used to fetch

https://github.com/processing/p5.js-website/blob/main/src/templates/pages/reference/data.json

and ... this?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/p5/tsconfig.json#L17-L20

Just use wget or curl can do this. I am not familiar with cli tools on windows. But even download them by hand was not a big deal. (I guess)

 But I don't know where I should place these two files.

**Comment by Zalastax** [comment]
I think it was only used to generate `data.json` from source. Since generating from source is no longer important, downloading `data.json` could be preferred. Node has easy to use libraries for fetching files which I think would be better than wget or curl.

The default path of data.json can be seen here: https://github.com/p5-types/p5.ts/blob/master/src/commands/generate.js

**Comment by wuyudi** [comment]
Now I have fixed download data.json.

![image](https://user-images.githubusercontent.com/30024051/209551516-7e97ff5b-8b21-46f2-aba6-59ea7e78a1f9.png)

download-p5.cjs

(To keep it simple, I skip the yargs lib.)

use cjs because upath doesn't support ESM.

```js
// https://stackoverflow.com/a/13544465
fs.mkdirSync(upath.joinSafe(__dirname, "../../p5/docs/reference/"), {
	recursive: true,
});
// https://stackoverflow.com/a/11944984
const file = fs.createWriteStream(
	upath.joinSafe(__dirname, "../../p5/docs/reference/data.json"),
);
const request = https.get(
	"https://raw.githubusercontent.com/processing/p5.js-website/main/src/templates/pages/reference/data.json",
	(response) => {
		response.pipe(file);

		// after download completed close filestream
		file.on("finish", () => {
			file.close();
			console.log("Download Completed");
		});
	},
)
```

What to do next?(I see the `await npmRun('grunt -- yuidoc', args.dir, args.npx);` in the code, but since

> Since generating from source is no longer important

So that maybe useless now?

**Comment by Zalastax** [comment]
From README:

To generate typings yourself, try out:
```
npm run download-p5
# npm run checkout <released-tag>
npm run generate-data
npm run generate
```
You have "completed" all but the last step:
```
npm run generate
```
I think you should even be able to rationalize the download of p5 to only be:
```
const request = https.get(
	"https://raw.githubusercontent.com/processing/p5.js-website/main/src/templates/pages/reference/data.json",
	(response) => {
		response.pipe(file);

		// after download completed close filestream
		file.on("finish", () => {
			file.close();
			console.log("Download Completed");
		});
	},
)
```

**Comment by wuyudi** [comment]
After some test, now

![image](https://user-images.githubusercontent.com/30024051/209568529-3126a6ea-b3e3-443e-8dcd-5ab32554811a.png)

```
❯ npm run generate

> p5.ts@1.0.0 generate
> node src/commands/generate.js

p5.Shader() src/webgl/p5.Shader.js, line 11, param "renderer" has invalid type: p5.RendererGL
UNKNOWN CLASS: JSON
UNKNOWN CLASS: console
MISSING: p5.RendererGL
MISSING: p5.Texture
```

found the test

```
❯ npm run test

> p5.ts@1.0.0 test
> ava


  ✔ split types
  ─

  1 test passed
```

It seems works well now?

**Comment by Zalastax** [comment]
Looks good! The remaining errors from generate need to be fixed here or in p5 but are not related to nodegit.
