### ISSUE TITLE
Update for p5.js 0.8.0

### ISSUE THREAD

**Issue by stephensmitchell** [p5-types/p5.ts#13]
Typings update for the latest version of https://github.com/processing/p5.js.

**Comment by Zemke** [comment]
Make a wish. :)

**Comment by Zemke** [comment]
There’s version 0.7.0 available at DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/p5

**Comment by Zalastax** [comment]
PR incoming: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37277
