### ISSUE TITLE
p5.Graphics class has no methods

### ISSUE THREAD

**Issue by PhasonMatrix** [p5-types/p5.ts#14]
`p5.createGrphics()`  returns an object of type `p5.Graphics`. In tutorials like [this](https://p5js.org/examples/structure-create-graphics.html) you can see that this object has drawing methods like `.background()` and `.ellipse()`. But in VSCode we can't get any IntelliSense on an object declared as type `p5.Graphics`, and have to make it type `any` to call drawing methods.

**Comment by Zalastax** [comment]
As far as I can see, those functions are not documented on http://p5js.org/reference/#/p5.Graphics or it's parents. For those functions to show up, they need to have YUIDoc. Do they have YUIDoc which I missed?

**Comment by PhasonMatrix** [comment]
Hi @Zalastax , no sorry. Hopefully, I haven't missed something. I can see that `p5.Graphics` inherits from `p5.Element` which also doesn't have these methods. Maybe documentation is not complete. My project is working fine if I declare my off-screen-image-buffer as `any` instead of `p5.Graphics` (`this.gfx:any = p.createGraphics(p.width, p.height);`). But, it would be nice to strongly type it.

**Comment by mikefowler** [comment]
@Zalastax @PhasonMatrix  it looks like the p5 prototype is mixed in to `p5.Graphics.js` on [these lines](https://github.com/processing/p5.js/blob/master/src/core/p5.Graphics.js#L33-L42).

Would adding`@extends p5` to the JSDocs of that file allow the types to be generated properly? I don't know too much about generating documentation from code comments.

**Comment by Zalastax** [comment]
@mikefowler, I believe so! I'll try it out this week. Good catch!

**Comment by Zalastax** [comment]
The answer is unfortunately no, it is not possible without hacks in the p5.ts codebase.
TypeScript doesn't support multiple 'extends' e.g. :
```TypeScript
class Graphics extends p5, Element  {
```
The workaround is [mixins](https://www.typescriptlang.org/docs/handbook/mixins.html), but that instead requires that we copy the definitions from p5 or Element into Graphics.
My solution is that I will write a guide on how to manually fix up the types after they have been generated.

**Comment by Zalastax** [comment]
I had a good thinking session and I figured out that we can use intersection types to make this work.
With my upcoming changes, the Graphics definition will become:
```TypeScript
declare module '../../index' {
    // Work-around for p5.Graphics inheriting from both p5 and p5.Element
    class __Graphics__ extends Element {
        /**
         *   Resets certain values such as those modified by
         *   functions in the Transform category and in the
         *   Lights category that are not automatically reset
         *   with graphics buffer objects. Calling this in
         *   draw() will copy the behavior of the standard
         *   canvas.
         */
        reset(): void;

        /**
         *   Removes a Graphics object from the page and frees
         *   any resources associated with it.
         */
        remove(): void;
    }
    // Work-around for p5.Graphics inheriting from both p5 and p5.Element
    type Graphics = __Graphics__ & p5;
}

```
With that change, Graphics can now be used both as an Element, as a p5 instance, and its own methods are available.
