### ISSUE TITLE
Would this same method work for p5-play?

### ISSUE THREAD

**Issue by DavidGriswoldTeacher** [p5-types/p5.ts#15]
I love using p5 with typescript, but I would like to fiddle with the p5.play library here: http://molleindustria.github.io/p5.play/. It does not have typings (that I can find) but it does use an automatic documenter of some kind. Would the techniques used to automatically generate the p5 typings also work on that library?

I am happy to contribute some time to actually making it happen if it's going to be possible, and I know it probably doesn't even belong in this project exactly, just don't want to spend hours barking up a tree you might already know how to leapfrog.

**Comment by Zalastax** [comment]
p5.play uses https://ace.c9.io/. I don't think it would be possible extend it to do what you want. I think that to achieve what you want, you would basically have to swap the editor for something else that supports TypeScript.

**Comment by DavidGriswoldTeacher** [comment]
I'm not sure you understood my question, sorry. I was talking about p5.play the library, not the editor embedded in the website. I use VS Code and Gitpod to interact with the p5 play library. All I am saying is that it does not provide d.ts files, and I would like to create them, so I was wondering if you could take a quick look at the p5.play code at its [github page](https://github.com/molleindustria/p5.play/) and let me know if you think your auto-generator would let me make a reasonable first pass on it. If so, I'll work on figuring out your parser and how to adapt it to the p5.play library.

**Comment by Zalastax** [comment]
I believe the answer is yes!

You'd need to find the `data.json` for p5.play, i.e. the equivalence to https://github.com/p5-types/p5.ts/blob/master/src/commands/generate.js#L13 (generated via https://github.com/p5-types/p5.ts/blob/master/src/commands/generate-data.js). I suspect the p5 file and the p5.play file will be quite similar.

Good luck and feel free to ask for help!

**Comment by DavidGriswoldTeacher** [comment]
Awesome, thanks! Not sure when I will get to this but I'm glad to know it
might be fruitful.

Thanks so much for your project, it is enabling me to use p5.js to teach a
high school computer science class where  I would have needed to use
processing otherwise. I like typescript and the web much more for this use.

**Comment by Zalastax** [comment]
Awesome!

Typescript is indeed very nice and how nice that this project has brought such joy!

**Comment by wuyudi** [comment]
https://github.com/Triton-Skywalker/Definition-File

This is a definition file for the p5.play.js library written in JavaScript

found this.
