### ISSUE TITLE
using loadSound in global mode?

### ISSUE THREAD

**Issue by DavidGriswoldTeacher** [p5-types/p5.ts#16]
I was playing with p5.sound, typescript in global mode, and keep getting an error in VS Code for `loadSound` not being found. Weirdly, it is able to autocomplete parameters if I type `loadSound(` but when I hover over it I get nothing and I get an error in the "Problems" section, so maybe it's pulling in the JS doc from the library manually? Either way, I'm confused on how to proceed. Maybe the `loadSound` function simply needs to be documented correctly in global.d.ts? Any suggestions?

**Comment by DavidGriswoldTeacher** [comment]
I was able to fix this problem in a js file with @ts-check enabled by adding the following to my personal global.d.ts:

```ts
declare global {
    declare function loadSound(
        path: string | any[],
        successCallback?: (...args: any[]) => any,
        errorCallback?: (...args: any[]) => any,
        whileLoading?: (...args: any[]) => any
    ): p5.SoundFile;
```

This code was copied directly from the p5.sound.d.ts . I tried to figure out how the parser works in terms of deciding which functions from p5.sound.d.ts and p5.dom.d.ts to add to global.d.ts, but I couldn't figure it out. The function declaration for `loadSound`, which does not get added to global.d.ts, didn't seem very different from the one for `soundFormats` - it just gets added to the p5.prototype on declaration - but it was not in the `p5InstanceExtensions` section of p5.sound.d.ts, even though `soundFormats` was.

**Comment by wuyudi** [comment]
now fixed.
