### ISSUE TITLE
Type definitions not automatically found by the compiler

### ISSUE THREAD

**Issue by Tompouce-onGit** [p5-types/p5.ts#17]
After installing the type definitions with `npm install --save-dev @types/p5`, typing some p5 code into the latest version of vscode doesn't show any intellisense types. This suggests that the typescript compiler can't find the definitions under `./node_modules/@types/p5`.

I know explicitly including references at the top of each file will work, but this seems like a noteworthy issue.

**Comment by Zalastax** [comment]
I believe it used to work. Where are other typings installed?

**Comment by vinkla** [comment]
Referenced issue from p5.js repository: https://github.com/processing/p5.js/issues/1339#issuecomment-498229272

**Comment by Zalastax** [comment]
I unfortunately don't know.

**Comment by PunkIslamist** [comment]
Just a note from my side: using p5 version 1.0.0 and @types/p5 version 0.9.1 works well.
In case it matters: I am using ES6 import syntax.

**Comment by antiboredom** [comment]
Hi @vinkla 

I've been trying to find a nice way to incorporate this into my [p5 vscode](https://marketplace.visualstudio.com/items?itemName=samplavigne.p5-vscode) extension. Have not _quite_ figured out the best way yet, but did discover that you can add the types globally to a project by creating a jsconfig.json file and adding this to it:

```json
{
  "include": [
    "*.js",
    "libraries/*.js",
    "node_modules/@types/p5/global.d.ts"
  ]
}
```
