### ISSUE TITLE
Warnings and errors when generating for p5 1.1.9

### ISSUE THREAD

**Issue by Zalastax** [p5-types/p5.ts#24]
```
λ npm run generate

> p5.ts@1.0.0 generate E:\Programming\node\p5.ts
> node src/cli.js generate

position() src/dom/dom.js, line 1732, required param "positionType" follows an optional param
userStartAudio() lib/addons/p5.sound.js, line 1257, param "element(s)" is not a valid JS symbol name
p5.Shader() src/webgl/p5.Shader.js, line 11, param "renderer" has invalid type: p5.RendererGL
userStartAudio() lib/addons/p5.sound.js, line 1257, param "element(s)" is not a valid JS symbol name
UNKNOWN CLASS: JSON
UNKNOWN CLASS: console
MISSING: p5.RendererGL
```
Probably needs corrections both in p5.js and p5.ts

**Comment by nharrer** [comment]
Also the generated files `index.d.ts` and `global.d.ts` reference `./lib/addons/p5.dom.d.ts`: 

    /// <reference path="./lib/addons/p5.dom.d.ts" />

But it does not exist (anymore). It seems to have moved to `./src/dom/dom.d.ts` which is already referenced further down.

Deleting those lines and ignoring the warnings you mentioned above, gave me a working version for 1.1.9 which I can use for now.

And thank you so much for that project. Working with p5 in Typescript is a huge pain without proper type checking and code completion in VS Code.

**Comment by pikeas** [comment]
Same issue here, @types/p5 is out-of-date so I tried using this repo to generate types for 1.2.0, which failed with the errors above.

**Comment by Zalastax** [comment]
Thanks for posting these updates! Let me know if you want to contribute and need help :)

**Comment by psalaets** [comment]
I'm interested in working on this issue.

It looks like there are two categories of fixes needed:

1. **Yuidoc corrections** - There are some issues in the p5 yuidoc that are causing the failures seen above. This requires a PR to the p5 repo.
2. **Unknown classes** - It looks like these come from the p5 source at `src/core/reference.js` which is a docs-only file. To handle these I am just going to ignore those classes the same way that [p5.sound is ignored](https://github.com/p5-types/p5.ts/blob/master/src/generate-typescript-annotations.js#L32).

Am I overlooking anything?

**Comment by wuyudi** [comment]
Any progress on this? :eyes:  , I am willing to fix some issues, but this project seems no longer maintained?

~~also, it seems that use jsdoc to generate .d.ts file is more stable?~~
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

**Comment by Zalastax** [comment]
Hi, I am indeed not maintaining this any longer. But if you contribute changes, I'll merge them and can eventually provide full access to you for long term maintenance.
