### ISSUE TITLE
Objects returned from create* DOM functions do not have element-specific methods

### ISSUE THREAD

**Issue by zqevans** [p5-types/p5.ts#26]
For functions like `createSelect()`, p5 will add additional methods like `.option()` and `.value()` to the base p5.Element object.

The typings for create* DOM functions like this currently just return p5.Element, so the compliler doesn't recognize the use of the element-specific functions.

It would be nice if `createSelect()` returned something like `p5.Slider` which extended `p5.Element` to include these extra properties and functions.

**Comment by Zalastax** [comment]
It would indeed be nice! The generated typings are based on the YUIDoc information from p5 so it would first have to be an improvement there! Could the YUIDoc for createSelect be modified to return something more specific?

**Comment by wuyudi** [comment]
the solution is:
1. patch by hand. But there are soooo many cases. (PR welcomed.)
2. fix the upstream. But now p5.js uses some old style which is hard to rewrite. See src/dom/dom.js
