### ISSUE TITLE
p5.MediaElement does not extend p5.Element

### ISSUE THREAD

**Issue by ngpeijiun** [p5-types/p5.ts#27]
According to this documentation:

https://github.com/processing/p5.js/wiki/Beyond-the-canvas#creating-html-media-elements

> There are also create methods for adding elements that deal with media—createVideo(), createAudio(), and createCapture(). These methods create a p5.MediaElement, which has some additional methods beyond those of a normal p5.Element.

To verify this, I have created the following code snippet. Note that it is able to call `hide()`, a method on p5.Element, on `mov` variable which holds a p5.MediaElement. So, intuitively we know that p5.MediaElement extends p5.Element:

```javascript
let playing = false
let mov
let button

const toggle = () => {
    if (playing) {
        mov.pause()
        button.html('play')
    } else {
        mov.loop()
        button.html('pause')
    }
    playing = !playing
}

function setup() {
    createCanvas(600, 300)
    background(100)
    mov = createVideo('https://file-examples-com.github.io/uploads/2018/04/file_example_MOV_640_800kB.mov')
    mov.hide()

    button = createButton('play')
    button.mousePressed(toggle)
}

function draw() {
    image(mov, 50, 50, 400, 200)
}
```

However, in typescript, the behavior is different, the `p5Types.MediaElement` does not have `hide()` method. In the following code snippet using typescript and react-p5, I have to convert the `p5Types.MediaElement` to `p5Types.Element` before the `hide()` method can be called. Similarly, `p5Types.MediaElement` also cannot be passed in as the first argument to `p5Types.image()` function, which accepts a type of `p5Types.Element`:

```typescript
import React from 'react'
import Sketch from 'react-p5'
import p5Types from 'p5'

let playing = false
let mov: p5Types.MediaElement
let button: p5Types.Element

function convertToElement(media: p5Types.MediaElement): p5Types.Element {
    return media as any as p5Types.Element
}

const toggle = () => {
    if (playing) {
        mov.pause()
        button.html('play')
    } else {
        mov.loop()
        button.html('pause')
    }
    playing = !playing
}

const setup = async (p5: p5Types, canvasParentRef: Element) => {
    p5.createCanvas(600, 300).parent(canvasParentRef)
    p5.background(100)

    mov = p5.createVideo('https://file-examples-com.github.io/uploads/2018/04/file_example_MOV_640_800kB.mov')
    convertToElement(mov).hide()

    button = p5.createButton('play')
    button.mousePressed(toggle)
}

const draw = (p5: p5Types) => {
    p5.image(convertToElement(mov), 50, 50, 400, 200)
}

const App: React.FC = () => <Sketch setup={setup} draw={draw} />

export default App
```

**Comment by Zalastax** [comment]
MediaElement seems to not have the @extends tag. Compare https://github.com/processing/p5.js/blob/e746833142157dcc2953cea635835e7f456f5988/src/dom/dom.js#L2310-L2312 to https://github.com/processing/p5.js/blob/3f0b2f0fe575dc81c724474154f5b23a517b7233/src/core/p5.Graphics.js#L17-L23. If it is fixed in p5.js and https://github.com/p5-types/p5.ts/issues/24 gets unblocked, then we can have a future release where this is corrected.

**Comment by ngpeijiun** [comment]
Has anyone communicated to p5.js side?

**Comment by Zalastax** [comment]
I don't think so.
