### ISSUE TITLE
constant typings

### ISSUE THREAD

**Issue by dcsan** [p5-types/p5.ts#39]
I'm having problems with basic constant typings.

I did see #3 but that seems more about extensions.

I'm having issues with simpler built in basic types like this:

```ts
  buffer.textAlign(p5.CENTER, p5.CENTER)
```

And I just get `undefined` for those values.
So somehow the static consts aren't getting .. exported/imported?
also intellisense doesn't work.

Other functions typing is working well.

## tsconfig.json

```
"preserveConstEnums": true,
```

## global.d.ts

```

// This file will add both p5 instanced and global intellisense
import module = require('p5');
import * as p5Global from 'p5/global'

export = module;
export as namespace p5;

declare global {
  interface Window {
    p5: typeof module,
    newToken: any
  }
}

```

## package.json has
```
  "devDependencies": {
    "@types/p5": "^0.9.1",

```

**Comment by wuyudi** [comment]
It works now.

![image](https://user-images.githubusercontent.com/30024051/209707828-e68173b1-a9f9-48be-961b-7e396288441a.png)
