### ISSUE TITLE
Declaration not containing P5 classes

### ISSUE THREAD

**Issue by JunoNgx** [p5-types/p5.ts#42]
I'm using JSDoc for light type checking in my p5js projects, and some (all?) of the P5 classes are not detected (such as `Vector` or `Color`).

For example, the following block is giving some errors in VSCode.

````javascript
/** @type { Vector } */ // red wavy underline
let midPosition;
/** @type { Color} */ // red wavy underline
let mainCol;
````
It is possible to perform an `import` as a workaround:

````javascript
/** @type { import("p5").Vector } */
let midPosition;
/** @type { import("p5").Color} */
let mainCol;
````

However, this is pretty ugly.

I don't understand TypeScript well enough to point out anything in particular, but my guess is these classes probably should have been declared somewhere. Is there any problem or side effect with doing so?

**Comment by wuyudi** [comment]
It seems fixed.

![image](https://user-images.githubusercontent.com/30024051/209708119-90eb970b-0042-4395-9bed-69b47c7a3441.png)
