### ISSUE TITLE
Webpack creates multiple instances of canvas, since p5 is imported from in different files

### ISSUE THREAD

**Issue by nxidplease** [p5-types/p5.ts#6]
When i run my sketch, setup is being called twice. I'm not sure why this happens but I'm quite sure it has something to do with importing classes from p5 in different files. I have 2 files: index.ts(contains the setup and draw functions) and Character.ts. In character.ts I import Vector from p5 and in index.ts p5 is imported just like the webpack-global example. When the script reaches the import Vector line it tries to redefine some functions on the window object(I get a lot of error messages from p5 code about it). I'm guessing it is pretty hard to fix this since we are stuck with the code that is called from the global scope...

**Comment by Zalastax** [comment]
If you create a gist/link to your repo I can take a look. Imports are cached so side-effects are not supposed to happen twice.

**Comment by Zalastax** [comment]
@nxidplease I'm closing this issue now due to inactivity. Feel free to re-open if the problem persists. I can help if you provide code I can look at.
