### ISSUE TITLE
Seem to be missing MediaElement in src/webgl/material.d.ts

### ISSUE THREAD

**Issue by jeremychone** [p5-types/p5.ts#9]
#### Environment

TypeScript 3.16
"@types/p5": "^0.7.1"
"p5": "^0.7.2"

#### Issue

When doing a simple `tsc` I get the following error
![image](https://user-images.githubusercontent.com/74671/48863226-843bb300-ed7d-11e8-925a-4216e8bbd34b.png)

(originally reported there: https://github.com/processing/p5.js/issues/3269)

**Comment by Zalastax** [comment]
Sorry for the confusion @jeremychone!
I believe that for `MediaElement` to be available you need to add a reference to `"@types/p5/lib/addons/p5.dom.d.ts"`. Let me know if that works! We need to fix this from our side but I don't know in what way yet.

The situation regarding p5 parts that are optional is unfortunate. I don't want to pollute the default scope with unavailable definitions (especially not global.d.ts) but I also want to provide a good out of the box experience.

For anyone reading, I would very much want help updating the documentation to use `@types/p5` and add an example that uses `p5.dom` without global mode - doing so should be fairly easy. I'll make sure to open issues about this in fair time but someone opening issues for me would be great too.

@Spongman should we just include all addons and global mode by default? Perhaps only the addons? Or maybe emit an empty interface for `MediaElement` (and others?) to trick compilation into working?

**Comment by Spongman** [comment]
i'd recommend just including the DOM types since they're referenced from the main types.

**Comment by Zalastax** [comment]
Alright, do you mind opening a PR?

**Comment by jeremychone** [comment]
btw, for others, the simplest way I found is to add the  `files` property in the  `tsconfig.json` as

```js
{
"compilerOptions": {...},
"files": ["./node_modules/@types/p5/lib/addons/p5.dom.d.ts"],
...
}
```
