### ISSUE TITLE
Generated type definitions of modules seems incorrect and doesn't work

### ISSUE THREAD

**Issue by Nyaacinth** [p5-types/p5.ts#96]
Related Discussion: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/63934

The file with issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/p5/lib/addons/p5.sound.d.ts

This auto-generated file seems incorrect, we cannot declare modules with a relative path, and it doesn't work at all. And seems like there’re some other definitions were written in the same way.

If I change the declaration to:
```ts
declare namespace p5sound {
  // ...
}

export = p5sound
```
It will then work properly.

**Comment by wuyudi** [comment]
seems relevant

https://github.com/p5-types/p5.ts/blob/a643bc4246c07d7ed92bf89ab62b0fe048dfe956/src/generate-typescript-annotations.ts#L417

PR welcomed. You can test the generated type directly in the https://github.com/p5-types/p5.ts/tree/master/examples/script folder.

**Comment by Nyaacinth** [comment]
> seems relevant
> 
> https://github.com/p5-types/p5.ts/blob/a643bc4246c07d7ed92bf89ab62b0fe048dfe956/src/generate-typescript-annotations.ts#L417
> 
> PR welcomed. You can test the generated type directly in the https://github.com/p5-types/p5.ts/tree/master/examples/script folder.

I found it's difficult to do this after looking at the sources.

Good Luck (xwx)/\

**Comment by wuyudi** [comment]
> I found it's difficult to do this after looking at the sources.

then any fix examples? for example, 

> If I change the declaration to:
>
> declare namespace p5sound {
>  // ...
> }
>
> export = p5sound
> It will then work properly.

change from what to what.

since it's possible to patch the output type files.
